### PR TITLE
Add Menu Gamepad Bindings

### PR DESCRIPTION
**Pull request by zicklag**
- Updates the leafwing-input-manager branch we are using to include
  latest API improvements. Check it out! Gamepad bindings are even cooler now!
- Updates buttons to have a visible focused state
- Allow controlling the menu focus with the gamepad.

It's now possible to fully navigate the game and menu without a mouse or keyboard, and you can tell when buttons are selected:

menu-highlight-buttons

---

I realized that since the commits I'm referencing for the leafwing-input-manager dependency are in my fork and not in the official repo on the master branch, once I delete my fork or branches, those commits will stop existing. It just breaks the ability to go back to any commit in history and build the game at that point.

Since we'll be hopefully getting the branch merged soon to master, where it will have a permanent commit ref, we may want to wait to merge this until that happens, unless you aren't really worried about a couple commits not having eternally reproducible builds.

### CODE REVIEW

**Comment by odecay** [comment]
What do you think? I say hold off at least for a day or 2 and see how your leafwing pr progresses. I will try to read thru the tread tomorrow and see if there is anyway I can contribute review. https://github.com/Leafwing-Studios/leafwing-input-manager/pull/151 this one right?

**Comment by alice-i-cecile** [comment]
FYI I'm planning to merge that branch soon, so reviews are much appreciated :) There will likely be further iteration over the next week or two once it's in, and then a 0.5 release just after the next Bevy major version.

**Comment by zicklag** [comment]
Yeah, getting extra review would be great! And we can just wait 'till the PR is merged.

It doesn't stop me from stacking other PRs on top of this one in the meantime anyway.

**Comment by zicklag** [comment]
Now that https://github.com/Leafwing-Studios/leafwing-input-manager/pull/151 was merged, I updated the dependency ref and this should be ready to merge.

**Pull request merged**
