### PR TITLE
Fix "puncy" typos

### PR DESCRIPTION
**Pull request by DRuppFv**
shouldn't it be "punchy"? haha

### CODE REVIEW

**Comment by 64kramsystem** [comment]
He :smile:  Thanks for the fix.

Actually, there's another occurrence of the same typo in the codebase, just in case you want to fix all of them. If you do, can you add the other fix to the same commit?

**Comment by DRuppFv** [comment]
> He smile Thanks for the fix.
> 
> Actually, there's another occurrence of the same typo in the codebase, just in case you want to fix all of them. If you do, can you add the other fix to the same commit?

Are you sure? I didn't find it.

**Comment by 64kramsystem** [comment]
> > He smile Thanks for the fix.
> > Actually, there's another occurrence of the same typo in the codebase, just in case you want to fix all of them. If you do, can you add the other fix to the same commit?
> 
> Are you sure? I didn't find that.

There you go!:

```
src/platform.rs:353:    const BROWSER_LOCAL_STORAGE_KEY: &str = "puncy-platform-storage";
```

**Comment by DRuppFv** [comment]
> > > He smile Thanks for the fix.
> > > Actually, there's another occurrence of the same typo in the codebase, just in case you want to fix all of them. If you do, can you add the other fix to the same commit?
> > 
> > 
> > Are you sure? I didn't find that.
> 
> There you go!:
> 
> ```
> src/platform.rs:353:    const BROWSER_LOCAL_STORAGE_KEY: &str = "puncy-platform-storage";
> ```

oh, i saw this, but i thought it was a normal word, not the game name, haha.
done!

**Review by 64kramsystem — APPROVED** [review]

**Comment by 64kramsystem** [comment]
I'll go for a squash commit in this case, since it doesn't add any value to have two commits for this fix.

**Comment by 64kramsystem** [comment]
@DRuppFv can you actually squash the two commits? then, I'll send to PR to the merge pipeline.

**Comment by zicklag** [comment]
Haha, good catch. Those are both my typos. For some reason I have a hard time typing the word punchy and my fingers want to leave out the `h`.

**Comment by 64kramsystem** [comment]
Thanks @DRuppFv :smile:

**Pull request merged**
