### PR TITLE
Update to Bevy 0.8 🎉

### PR DESCRIPTION
**Pull request by zicklag**
It works on Bevy 0.8!

Currently we're depending on the Bevy default features, but that pulls a lot more than we need. I'm going to follow up with a PR to try and cut that down. We have some dependencies depending on Bevy UI, PBR, and Audio, I think and I need to figure out which ones.

### CODE REVIEW

**Review by 64kramsystem — APPROVED** [review]

**Review by odecay — COMMENTED** [review]
Looks good to me :+1:
we will be waiting on the debug stuff to return, looks like `--features=debug` wont work till then

**Comment by zicklag** [comment]
Yep, we can follow up with that as soon as those crates update, and we might as well tackle #144 at the same time.

**Comment by odecay** [comment]
> Yep, we can follow up with that as soon as those crates update, and we might as well tackle #144 at the same time.

sounds good

**Comment by odecay** [comment]
[pr for update on bevy-egui-inspector](https://github.com/jakobhellermann/bevy-inspector-egui/pull/76)

**Pull request merged**
