### PR TITLE
Add GitHub workflow for automated binary releases

### PR DESCRIPTION
**Pull request by orhun**
This PR adds a release workflow for creating binary archives when a tag is pushed. It is required for the launcher, see #103

As an example, see the release assets created on my fork: https://github.com/orhun/punchy/releases/tag/v0.0.3

### CODE REVIEW

**Review by zicklag — APPROVED** [review]
Awesome, thanks!

**Comment by odecay** [comment]
I'm wondering if it may be worthwhile axing the windows i686 build to save CI time?

**Comment by erlend-sh** [comment]
I’m on board with axing windows i686. They have the option of building themselves or using the web build anyhow.

**Review by 64kramsystem — APPROVED** [review]
Ok, this can go in also for me, with the i686 removed.

-----

We'll see how much resources this takes. If it takes too much resources, we have a couple of things that can help. For the "future selves", in case we'll need them, they are:

1. disable caching, since the caches will likely not be effective anyway; this way, we'll avoid them interfere with the `cargo check` caches
2. use the `master` branch cache for the ubuntu build.

**Review by 64kramsystem — APPROVED** [review]
Good to merge for me :smile: :+1:

**Comment by orhun** [comment]
PR is updated in 8df4080929dc029d59d678447e04009822b6cae7

This means that users who run the launcher on Windows i686 won't be able to play `punchy`, but that's rather a minority so I agree with removing i686 for improving the build times.

**Comment by 64kramsystem** [comment]
Well, turns out, I was wrong on the cache size :star_struck: 

I've confused Github "storage" with "caches", which are separated. Cache limit is [10 GB](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy), so we don't need to worry at all :sweat_smile:

**Comment by 64kramsystem** [comment]
Ok, it seems that I was also wrong on the available workflow running time available 🤬

It seems that public repositories don't have time budgets, but only constraints on how many runners run concurrently (see [here](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits)).

In short: we won't have any problem unless we the PR workflows start to pile up (which I think won't happen, at least for a long time) :smile:

**Comment by zicklag** [comment]
Ah, that makes a lot of sense how Bevy get's away with it then! With 284 open pull requests I thought they'd have run out by now. :laughing:

**Pull request merged**
